Feat/maintenance report
EyeSeeTea/d2-reports pull request #130
Opened 2023-12-11 22:10 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/860rv3gg5

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

https://github.com/EyeSeeTea/d2-reports/assets/37223065/30558258-65fe-49ab-a8f2-4e1693738703

### :fire: Notes to the tester
```
REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238/
REACT_APP_REPORT_VARIANT=glass-admin
```

2023-12-12 12:38 UTC, tokland reviewed
Looking good, some in-line comments, mostly minor issues.

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +    async delete(namespace: string, items: Id[]): Promise<void> {
items -> itemIds. But item is too generic, what is the entity we are working with?

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +            })
We should use `this.api.models.organisationUnits` or `this.api.metadata.get({organisationUnits: ...})`

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +            }))
All is the same, no need to map.

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +            .map(upload => ({
be consistent: files/upload, should be the same, one plural, the other singular.

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +                return _.assign({}, upload, { status: status });
`{...upload, {status: status}}`

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +    }
Implement logic in entity: PaginatedObjects

2023-12-12 12:38 UTC, tokland commented on src/data/reports/glass-admin/GLASSDataMaintenanceDefaultRepository.ts
> +const emptyPage = {
When definining literal objects, be explicit with the type so TS can help you: `: GLASSMaintenancePaginatedObjects<GLASSDataMaintenanceItem>`

2023-12-12 12:38 UTC, tokland commented on src/domain/reports/glass-admin/entities/GLASSDataMaintenanceItem.tsx
> +        approveAccess?: NamedRef[];
As a general rule, minimize optional properties. I guess this comes from data not being set in the data store. Then the solution is setting default values when loading from the data store. 

That said, if unsure, keep it as is.

2023-12-12 12:38 UTC, tokland commented on src/domain/reports/glass-admin/repositories/GLASSDataMaintenanceRepository.ts
> +    module: Module | "";
As a general rule, `| ""` looks weird. Typically you'd write `Module | undefined` (not sure in this particular scenario)

2023-12-12 12:38 UTC, tokland commented on src/domain/reports/glass-admin/usecases/UpdateGLASSDataMaintenanceUseCase.ts
> +export class UpdateGLASSDataMaintenanceUseCase implements UseCase {
We used to do this "implements UseCase", but we have noticied it hinders code navigation while adding very little value, so better just to remove it.

2023-12-12 12:38 UTC, tokland commented on src/domain/reports/glass-admin/usecases/UpdateGLASSDataMaintenanceUseCase.ts
> +            case "delete":
No need to change it, but typically we create separate use cases, avoid catch-all use cases.

2023-12-12 12:38 UTC, tokland commented on src/webapp/reports/glass-admin/glass-admin-list/DataMaintenanceList.tsx
> +                    <Button onClick={async () => deleteFiles(filesToDelete)} color="primary" variant="contained">
No need for async. Move to useCallback

2023-12-12 12:38 UTC, tokland commented on src/webapp/reports/glass-admin/glass-admin-list/useFiles.tsx
> +    }
Move all these useMemo / useCallback to custom hooks. This reduces lines count and make the render block more declarative.

2023-12-12 12:38 UTC, tokland commented on src/webapp/reports/glass-admin/glass-admin-list/useFiles.tsx
> +        () => async (_search: string, paging: TablePagination, sorting: TableSorting<DataMaintenanceViewModel>) => {
A useMemo of a function is typically a useCallback.

2023-12-13 11:17 UTC, tokland approved these changes
Thanks! Some minor comments, but code-wise, ready for merging

2023-12-13 11:17 UTC, tokland commented on src/domain/reports/glass-admin/entities/GLASSDataMaintenanceItem.tsx
> +export function getUserModules(modules: GLASSModule[], user: User) {
[good practices] Explicit return type

2023-12-13 11:17 UTC, tokland commented on src/webapp/reports/glass-admin/glass-admin-list/useDeleteFiles.tsx
> +        },
The function is defined as async, but no await is used. As it is, `reload` is executed without waiting fot updateState to finish, is that correct?

2024-02-13 14:06 UTC, ifoche requested changes
@deeonwuli a couple of comments:
- Please do not show anything until a module has been selected in the dropdown
- The ATC classification tab should only show up under AMC module selection

Could you please take care of this? 

Thank you!

2024-02-16 19:34 UTC, ifoche approved these changes
thanks @deeonwuli

2024-02-16 19:34 UTC, merged