add excludeRolesByUsers exclusion rule
EyeSeeTea/d2-reports pull request #145
Opened 2024-04-15 17:48 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes #?

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

### :fire: Notes to the tester

2024-09-02 11:00 UTC, idelcano commented
I have merged development and fixed the workflow of the rules, also i have included excludedRolesByGroups
I have created this matrix to test it:
https://docs.google.com/spreadsheets/d/11dnC4BQ-oNA_67bjkCJbws1YRzcfJWk4pnYJ63c4l_k/edit?gid=0#gid=0

and the variant to make it work is:
REACT_APP_REPORT_VARIANT=authorities-monitoring

Its already installed in dev: 
https://extranet.who.int/dhis2-dev/dhis-web-reports/index.html#/standard-report/view/ctfks02sZka

2024-09-06 10:22 UTC, nshandra commented on src/data/reports/authorities-monitoring/AuthoritiesMonitoringDefaultRepository.ts
> +        debugger;
@idelcano This is leftover code, right?

2024-09-06 13:01 UTC, nshandra requested changes
Looks ok, aside from the leftover code mentioned.

2024-09-11 14:51 UTC, nshandra approved these changes
Looks good. Approved.

2024-09-16 08:51 UTC, merged